version : '3.8'

services:
  ligamx: #Nombre de la app (el que esta en el properties)
    build: .  #Directorio donde se puede encontrar el Dockerfile
    restart: always
    container_name: spring_ligamx
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DDL_AUTO: ${DDL_AUTO}
      SQL: ${SQL}
      GENERATE_USER: ${GENERATE_USER}
      PRIVATE_KEY: ${PRIVATE_KEY}

  mysql:
    image: mysql:8
    restart: always
    container_name: mysql_ligamx
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: