spring.application.name=ligamx

#Configuraciones de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA e Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}
spring.jpa.show-sql=${SQL}

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

#Configuraciones del JWT
security.jwt.key.private=${PRIVATE_KEY}
security.jwt.user.generator=${GENERATE_USER}