spring.application.name=ligamx

#Configuraciones de la base de datos
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=${DRIVER_DB}

#JPA e Hibernate
spring.jpa.hibernate.ddl-auto:update
spring.jpa.show-sql=true

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

#Configuraciones del JWT
security.jwt.key.private=${PRIVATE_KEY}
security.jwt.user.generator=${GENERATE_USER}